In [1]:
import pandas as pd
from scipy.spatial.distance import euclidean
df = pd.read_csv("USA_cars_datasets.csv")


df['mileage'] = df['mileage'].replace(0.0, df.mileage.median())
df['price'] = df['price'].replace(0.0, df.price.median())


df.brand.unique()
df['brand'] = df['brand'].map({
    'mercedes-benz': 1,
    'bmw':2,
    'lexus':3,
    'infitini':4,
    'jaguar':5,
    'toyota':6,
    'nissan':7,
    'ford':8,
    'chevrolet':9,
    'lincoln':10,
    'maserati':11,
    'dodge':12,
    'jeep':13,
    'gmc':14,
    'honda':15,
    'audi':16,
    'chrysler':17,
    'mazda':18,
    'hyundai':19,
    'kia':20,
    'ram':21,
    'land':22,
    'peterbilt':23,
    'harley-division':24,
    'buick':25,
    'cadillac':26,
    'heartland':27,
    'acura':28
})
df.head()

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,6.0,cruiser,2008,clean vehicle,274117.0,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,8.0,se,2011,clean vehicle,190552.0,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,12.0,mpv,2018,clean vehicle,39590.0,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,8.0,door,2014,clean vehicle,64146.0,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,9.0,1500,2018,clean vehicle,6654.0,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [2]:
features = ['mileage', 'brand', 'price', 'year']
df = df[features]
df.head(15)
df.dropna(inplace=True)
# df.max()

In [6]:
perfect_car = {'mileage': 5000, 'brand': 1, 'price':3000, 'year':2020}
perfect_car = pd.DataFrame([perfect_car])

def inverse_distance_similarity(carA, carB):
    euclidean_dist = euclidean(carA, carB)
    similarity = 1 / (1 + euclidean_dist)
    return similarity

distances = []
similarities = []
for i in range(len(df)):
    distance = euclidean(df.iloc[i].values.reshape(1, -1), perfect_car.iloc[:i+1].values.reshape(1,-1))
    distances.append(distance)
    similarities.append(inverse_distance_similarity(df.iloc[i].values.reshape(1, -1), perfect_car.reshape(1, -1)))
df['distance'] = distances
df['similarity'] = similarities

sorted_df = df.sort_values(by='similarity', ascending=False)

print(sorted_df)

ValueError: Input vector should be 1-D.